# Generated by Django 3.2.18 on 2023-03-28 19:10

import bookwyrm.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0180_auto_20230327_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='venue',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='venue',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True),
        ),
    ]
