# Generated by Django 3.2.18 on 2023-03-28 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0181_auto_20230328_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='venue',
        ),
    ]
