# Generated by Django 3.2.18 on 2023-04-03 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0178_auto_20230328_2132'),
        ('bookwyrm', '0182_remove_author_venue'),
    ]

    operations = [
    ]
