# Generated by Django 3.2.18 on 2023-04-03 01:56

import bookwyrm.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0183_merge_20230403_0148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='bnf_id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='bnf_id',
        ),
        migrations.AddField(
            model_name='book',
            name='arxiv_id',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=128, null=True),
        ),
    ]
